// generated by qbg -usedatastorewrapper -output model_query.go .; DO NOT EDIT

package main

import (
	"go.mercari.io/datastore"
)

// Plugin supply hook point for query constructions.
type Plugin interface {
	Init(typeName string)
	Ancestor(ancestor datastore.Key)
	KeysOnly()
	Start(cur datastore.Cursor)
	Offset(offset int)
	Limit(limit int)
	Filter(name, op string, value interface{})
	Asc(name string)
	Desc(name string)
}

// Plugger supply Plugin component.
type Plugger interface {
	Plugin() Plugin
}

// BQLoadJobQueryBuilder build query for BQLoadJob.
type BQLoadJobQueryBuilder struct {
	q              datastore.Query
	plugin         Plugin
	JobID          *BQLoadJobQueryProperty
	Kind           *BQLoadJobQueryProperty
	Status         *BQLoadJobQueryProperty
	ChangeStatusAt *BQLoadJobQueryProperty
	CreatedAt      *BQLoadJobQueryProperty
	UpdatedAt      *BQLoadJobQueryProperty
	SchemaVersion  *BQLoadJobQueryProperty
}

// BQLoadJobQueryProperty has property information for BQLoadJobQueryBuilder.
type BQLoadJobQueryProperty struct {
	bldr *BQLoadJobQueryBuilder
	name string
}

// NewBQLoadJobQueryBuilder create new BQLoadJobQueryBuilder.
func NewBQLoadJobQueryBuilder(client datastore.Client) *BQLoadJobQueryBuilder {
	return NewBQLoadJobQueryBuilderWithKind(client, "BQLoadJob")
}

// NewBQLoadJobQueryBuilderWithKind create new BQLoadJobQueryBuilder with specific kind.
func NewBQLoadJobQueryBuilderWithKind(client datastore.Client, kind string) *BQLoadJobQueryBuilder {
	q := client.NewQuery(kind)
	bldr := &BQLoadJobQueryBuilder{q: q}
	bldr.JobID = &BQLoadJobQueryProperty{
		bldr: bldr,
		name: "JobID",
	}
	bldr.Kind = &BQLoadJobQueryProperty{
		bldr: bldr,
		name: "Kind",
	}
	bldr.Status = &BQLoadJobQueryProperty{
		bldr: bldr,
		name: "Status",
	}
	bldr.ChangeStatusAt = &BQLoadJobQueryProperty{
		bldr: bldr,
		name: "ChangeStatusAt",
	}
	bldr.CreatedAt = &BQLoadJobQueryProperty{
		bldr: bldr,
		name: "CreatedAt",
	}
	bldr.UpdatedAt = &BQLoadJobQueryProperty{
		bldr: bldr,
		name: "UpdatedAt",
	}
	bldr.SchemaVersion = &BQLoadJobQueryProperty{
		bldr: bldr,
		name: "SchemaVersion",
	}

	if plugger, ok := interface{}(bldr).(Plugger); ok {
		bldr.plugin = plugger.Plugin()
		bldr.plugin.Init("BQLoadJob")
	}

	return bldr
}

// Ancestor sets parent key to ancestor query.
func (bldr *BQLoadJobQueryBuilder) Ancestor(parentKey datastore.Key) *BQLoadJobQueryBuilder {
	bldr.q = bldr.q.Ancestor(parentKey)
	if bldr.plugin != nil {
		bldr.plugin.Ancestor(parentKey)
	}
	return bldr
}

// KeysOnly sets keys only option to query.
func (bldr *BQLoadJobQueryBuilder) KeysOnly() *BQLoadJobQueryBuilder {
	bldr.q = bldr.q.KeysOnly()
	if bldr.plugin != nil {
		bldr.plugin.KeysOnly()
	}
	return bldr
}

// Start setup to query.
func (bldr *BQLoadJobQueryBuilder) Start(cur datastore.Cursor) *BQLoadJobQueryBuilder {
	bldr.q = bldr.q.Start(cur)
	if bldr.plugin != nil {
		bldr.plugin.Start(cur)
	}
	return bldr
}

// Offset setup to query.
func (bldr *BQLoadJobQueryBuilder) Offset(offset int) *BQLoadJobQueryBuilder {
	bldr.q = bldr.q.Offset(offset)
	if bldr.plugin != nil {
		bldr.plugin.Offset(offset)
	}
	return bldr
}

// Limit setup to query.
func (bldr *BQLoadJobQueryBuilder) Limit(limit int) *BQLoadJobQueryBuilder {
	bldr.q = bldr.q.Limit(limit)
	if bldr.plugin != nil {
		bldr.plugin.Limit(limit)
	}
	return bldr
}

// Query returns *datastore.Query.
func (bldr *BQLoadJobQueryBuilder) Query() datastore.Query {
	return bldr.q
}

// Filter with op & value.
func (p *BQLoadJobQueryProperty) Filter(op string, value interface{}) *BQLoadJobQueryBuilder {
	switch op {
	case "<=":
		p.LessThanOrEqual(value)
	case ">=":
		p.GreaterThanOrEqual(value)
	case "<":
		p.LessThan(value)
	case ">":
		p.GreaterThan(value)
	case "=":
		p.Equal(value)
	default:
		p.bldr.q = p.bldr.q.Filter(p.name+" "+op, value) // error raised by native query
	}
	if p.bldr.plugin != nil {
		p.bldr.plugin.Filter(p.name, op, value)
	}
	return p.bldr
}

// LessThanOrEqual filter with value.
func (p *BQLoadJobQueryProperty) LessThanOrEqual(value interface{}) *BQLoadJobQueryBuilder {
	p.bldr.q = p.bldr.q.Filter(p.name+" <=", value)
	if p.bldr.plugin != nil {
		p.bldr.plugin.Filter(p.name, "<=", value)
	}
	return p.bldr
}

// GreaterThanOrEqual filter with value.
func (p *BQLoadJobQueryProperty) GreaterThanOrEqual(value interface{}) *BQLoadJobQueryBuilder {
	p.bldr.q = p.bldr.q.Filter(p.name+" >=", value)
	if p.bldr.plugin != nil {
		p.bldr.plugin.Filter(p.name, ">=", value)
	}
	return p.bldr
}

// LessThan filter with value.
func (p *BQLoadJobQueryProperty) LessThan(value interface{}) *BQLoadJobQueryBuilder {
	p.bldr.q = p.bldr.q.Filter(p.name+" <", value)
	if p.bldr.plugin != nil {
		p.bldr.plugin.Filter(p.name, "<", value)
	}
	return p.bldr
}

// GreaterThan filter with value.
func (p *BQLoadJobQueryProperty) GreaterThan(value interface{}) *BQLoadJobQueryBuilder {
	p.bldr.q = p.bldr.q.Filter(p.name+" >", value)
	if p.bldr.plugin != nil {
		p.bldr.plugin.Filter(p.name, ">", value)
	}
	return p.bldr
}

// Equal filter with value.
func (p *BQLoadJobQueryProperty) Equal(value interface{}) *BQLoadJobQueryBuilder {
	p.bldr.q = p.bldr.q.Filter(p.name+" =", value)
	if p.bldr.plugin != nil {
		p.bldr.plugin.Filter(p.name, "=", value)
	}
	return p.bldr
}

// Asc order.
func (p *BQLoadJobQueryProperty) Asc() *BQLoadJobQueryBuilder {
	p.bldr.q = p.bldr.q.Order(p.name)
	if p.bldr.plugin != nil {
		p.bldr.plugin.Asc(p.name)
	}
	return p.bldr
}

// Desc order.
func (p *BQLoadJobQueryProperty) Desc() *BQLoadJobQueryBuilder {
	p.bldr.q = p.bldr.q.Order("-" + p.name)
	if p.bldr.plugin != nil {
		p.bldr.plugin.Desc(p.name)
	}
	return p.bldr
}
